#!/usr/bin/env bash

set -e

# Arguement parsing
# =================

clean=false
deps=false
runner=(pytest -n 4)
while [[  $# -ne 0 ]]; do case "$1" in
    clean) clean=true          ;;
     deps) deps=true           ;;
     kplc) runner=( bin/kplc ) ;;
        *) break               ;;
esac; shift; done

            targets=( )
! $deps  || targets+=( deps )
            targets+=( execution translation translate-to-iele )

# Main
# ====

! $clean || rm -rf .build/
source bin/activate
make -j4 "${targets[@]}"
exec "${runner[@]}" "$@"
