#!/usr/bin/env bash

# Usage
# =====
#
# Execute ninja:
#
#   ./build <arguments-to-ninja>
#
# Execute arbitary command in fully set up environment
#
#   ./build -- <arbitary-command>

set -eu     # Fail on non-zero exit code, undefined variable

base="$(cd "$(dirname "$0")"; pwd)"
build_dir="$base/.build"

# Helpers
# =======

log()  { echo >&2 "=== " $@ ; }
fail() { log "$@"; exit 1   ; }

# Generate Ninja build file
# =========================

generate_ninja() {
    export PYTHONPATH="$base/ext/"
    [ -x "$base/ext/kninja/.git" ] || git submodule update --init "$base/ext/kninja/"
    python3 "$base/lib/build.py"
}

# Main
# ====

type -t ninja > /dev/null || fail "ninja-build not available. Giving up."
generate_ninja
[[ $# -lt 1 ]] || [[ -- != $1 ]] || { shift ; exec "$@" ; }
exec ninja -f "$base/.build/generated.ninja" "$@"
