name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default:
  distro:
    description: 'Distribution to setup Docker for.'
    required: true
  z3-version:
    description: 'Z3 version to use.'
    required: false
    default: 4.8.15
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
      BASE_IMAGE: ${{ inputs.distro }}
      Z3_VERSION: ${{ inputs.z3-version }}
    run: |
      set -euxo pipefail

      K_VERSION=$(cat ${SUBDIR}deps/k_release)

      docker build . \
          --build-arg USER=$(id -un) --build-arg USER_ID=$(id -u)   \
          --build-arg GROUP=$(id -gn) --build-arg GROUP_ID=$(id -g) \
          --build-arg BASE_IMAGE=${BASE_IMAGE}                      \
          --tag z3:${Z3_VERSION}                                    \
          --file ${SUBDIR}.github/workflows/Dockerfile.z3

      docker build . --file ${SUBDIR}.github/workflows/Dockerfile    \
          --tag runtimeverification/${TAG_NAME}                      \
          --build-arg BASE_IMAGE=${BASE_IMAGE}                       \
          --build-arg Z3_VERSION=${Z3_VERSION}                       \
          --build-arg K_VERSION=${K_VERSION}                         \
          --build-arg USER=$(id -un) --build-arg USER_ID=$(id -u)    \
          --build-arg GROUP=$(id -gn) --build-arg GROUP_ID=$(id -g)

      docker run                             \
          --name ${TAG_NAME}                 \
          --rm                               \
          --interactive                      \
          --tty                              \
          --detach                           \
          --workdir /opt/workspace/${SUBDIR} \
          --user root                        \
          runtimeverification/${TAG_NAME}

      docker cp . ${TAG_NAME}:/opt/workspace/${SUBDIR}
      docker exec ${TAG_NAME} chown -R user:user /opt/workspace/${SUBDIR}
      