name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps_runtimeverification_k'
      - '_update-deps_runtimeverification_blockchain-k-plugin'
      - '_update-deps_runtimeverification_pyk'
      - 'nix-flake'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update K version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Update K release tag'
        run: |
          cd deps/k
          git fetch --tags
          cd -
          K_VERSION="$(cd deps/k && git tag --points-at HEAD | cut --characters='2-')"
          echo "${K_VERSION}" > deps/k_release
          git add deps/k_release && git commit -m 'deps/k_release: update release file' || true
      - name: 'Update pyk release tag'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          pyk_version="$(cat deps/pyk_release)"
          sed -i 's!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="[v0-9\.]*" }!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="'${pyk_version}'" }!' kplutus-pyk/pyproject.toml
          sed -i 's!    pyk.url = "github:runtimeverification/pyk/[v0-9\.]*"!    pyk.url = "github:runtimeverification/pyk/'"${pyk_version}"'"!' flake.nix
          cd kplutus-pyk
          poetry update
          cd -
          git add kplutus-pyk/ && git commit -m 'kplutus-pyk/: sync poetry files' || true
      - name: 'Update plugin release tag'
        run: |
          cd deps/blockchain-k-plugin
          rev=$(git rev-parse HEAD)
          cd -
          echo ${rev} > deps/blockchain-k-plugin_release
          sed -i 's!    blockchain-k-plugin.url = "github:runtimeverification/blockchain-k-plugin/[0-9a-f]*"!    blockchain-k-plugin.url = "github:runtimeverification/blockchain-k-plugin/'"${rev}"'"!' flake.nix
          git add deps/blockchain-k-plugin_release && git commit -m 'deps/blockchain-k-plugin_release: update release file' || true
      - name: 'Install Nix/Cachix'
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@v10
        with:
          name: k-framework
          authToken: '${{ secrets.CACHIX_PUBLIC_KEY }}'
      - name: 'Update nix flake inputs'
        run: |
          nix run .#update-from-submodules
          nix flake update
          git add flake.nix flake.lock && git commit -m 'flake.{nix,lock}: update Nix derivations' || true
      - name: 'Push updates'
        run: git push
